# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build web app
      run: npm run build

    - name: Set deploy key
      run: mkdir ~/.ssh && echo "${{ secrets.SERVER_SSH_KEY }}" > ${{ secrets.LOCAL_DEPLOY_KEY_DESTINATION }} && chmod 600 ${{ secrets.LOCAL_DEPLOY_KEY_DESTINATION }}

    - name: Deploy app
      run: rsync -e "ssh -i ${{ secrets.LOCAL_DEPLOY_KEY_DESTINATION }} -o StrictHostKeyChecking=no" --force -azd ./public/ ${{ secrets.SERVER_SSH_USER }}:${{ secrets.SERVER_DESTINATION }} --delete
